name: With Parameters
on:
  workflow_dispatch:
    inputs:
      param1:
        description: Write the words describing humans
        required: true
        default: ascetic
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input Parameters
        run: |
          echo "Print the input parameters ${{ github.event.inputs.param1 }}"
  
