name: Trigger manually
on:
  issues:
    types:
      - opened
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print echo
        run: |
          echo "This is run by workfow dispatch"
  
