name: nodejs installation
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: list files
        run: ls -al
      # - name: npm install
      #   run: |
      #     cd ./github-actions-learn/github-actions-learn/
      #     npm install
      # - name: install dependencies
      #   run: |
      #     cd ./github-actions-learn/github-actions-learn/ 
      #     npm ci
      # - name: npm build
      #   run: npm run buld
      # - name: deploy the application
      #   run: npm run deploy
      #   if: github.refs == 'refs/heads/main' && github.event_name == 'push'
